app = "tg-task-bot"
primary_region = "gru"

# [http_service]
#   internal_port = 8080
#   auto_start_machines = true
#   auto_stop_machines = false
#   force_https = true
#   min_machines_running = 1
#   processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"